In [89]:
import os
import torch
import mlflow
import numpy as np
import pandas as pd

from collections import Counter
from tqdm import tqdm
from transformers.data.data_collator import DataCollatorWithPadding
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoModelForTokenClassification, EvalPrediction
from transformers import TrainingArguments, Trainer
from sklearn.metrics import accuracy_score, classification_report, precision_recall_fscore_support
from datasets import load_dataset

In [167]:
# Load dataset
suffix = "1_1"
usecase = "atis"
filename = f"../{usecase}/processed/"

train_df = pd.read_csv(filename + f"ner_train_v{suffix}.csv")
valid_df = pd.read_csv(filename + f"ner_valid_v{suffix}.csv")
test_df = pd.read_csv(filename + f"ner_test_v{suffix}.csv")

# train_df = pd.read_parquet("../data/ner/mia/v5_14k5_train_75p_loc_v3.parquet")
# valid_df = pd.read_parquet("../data/ner/mia/v5_14k5_val_15p_loc_v3.parquet")
# test_df = pd.read_parquet("../data/ner/mia/v5_14k5_test_10p_loc_v3.parquet")

df = pd.concat([train_df, valid_df, test_df], axis=0)
df

,text,ne,intent,ne_tokens
0,i want to fly from baltimore to dallas round trip,O O O O O B-fromloc.city_name O B-toloc.city_n...,atis_flight,O O O O O B-fromloc.city_name I-fromloc.city_n...
1,round trip fares from baltimore to philadelphi...,B-round_trip I-round_trip O O B-fromloc.city_n...,atis_airfare,B-round_trip I-round_trip O O B-fromloc.city_n...
2,show me the flights arriving on baltimore on j...,O O O O O O B-toloc.city_name O B-arrive_date....,atis_flight,O O O O O O B-toloc.city_name I-toloc.city_nam...
3,what are the flights which depart from san fra...,O O O O O O O B-fromloc.city_name I-fromloc.ci...,atis_flight,O O O O O O O B-fromloc.city_name I-fromloc.ci...
4,which airlines fly from boston to washington d...,O O O O B-fromloc.city_name O B-toloc.city_nam...,atis_airline,O O O O B-fromloc.city_name I-fromloc.city_nam...
...,...,...,...,...
888,please find all the flights from cincinnati to...,O O O O O O B-fromloc.city_name O O O O O B-to...,atis_flight,O O O O O O B-fromloc.city_name I-fromloc.city...
889,find me a flight from cincinnati to any airpor...,O O O O O B-fromloc.city_name O O O O O B-tolo...,atis_flight,O O O O O B-fromloc.city_name I-fromloc.city_n...
890,i'd like to fly from miami to chicago on ameri...,O O O O O B-fromloc.city_name O B-toloc.city_n...,atis_flight,O O O O O O B-fromloc.city_name I-fromloc.city...
891,i would like to book a round trip flight from ...,O O O O O O B-round_trip I-round_trip O O B-fr...,atis_flight,O O O O O O B-round_trip I-round_trip O O B-fr...
892,find me a flight that flies from memphis to ta...,O O O O O O O B-fromloc.city_name O B-toloc.ci...,atis_flight,O O O O O O O B-fromloc.city_name I-fromloc.ci...

In [3]:
# Extract utterances and name entities to train data and labels separately
# "ne_tokens" contains the name entities after preprocessings(make sure we get the same size as tokenized texts)

X_train = train_df["text"]
y_train = train_df["ne_tokens"]

X_valid = valid_df["text"]
y_valid = valid_df["ne_tokens"]

X_test = test_df["text"]
y_test = test_df["ne_tokens"]

# X_train = train_df['reduced_sent']
# y_train = train_df['io_tags']

# X_valid = valid_df['reduced_sent']
# y_valid = valid_df['io_tags']

# X_test = test_df['reduced_sent']
# y_test = test_df['io_tags']

print(f"Trainset: {len(y_train)}\nValidset: {len(y_valid)}\nTestset: {len(y_test)}")

Trainset: 4478
Validset: 500
Testset: 893

In [44]:
def encode_and_pad_y(X_encoded, input_tags, mapping):
    '''
    Turn string labels into numbers and pad
    
    Args:
        X_encoded: batch encoded output from tokenizer
        input_tags: list of list of strings that are labels to X_encoded
        mapping: dictionary of labels and their corresponding numbers
    
    Returns: list of list of numbers
    '''
    y_encoded = []
    for X, y_str in zip(X_encoded['input_ids'], input_tags):  # input_ids are the tokenized results, should be a list of numbers
        y = y_str.split(" ")  # input_tags are "ne_tokens" in our original files, convert strings to list
        y_ids = [mapping[tag] for tag in y]  # map every ne_token to number, since we could only use numbers in our training
        y_padded = y_ids + [mapping['O']] * (len(X) - len(y_ids))  # Make sure label_ids have the same size as input_ids
        y_encoded.append(y_padded)  # concatenate all label_ids together

    return y_encoded

def tokens2features(
    batch_encoding,
    labels
):
    """
    Parse BatchEncoding object into list of CustomInputFeatures to ingest in model.

    Args:
        batch_encoding: encoding of a list of text from tokenizer
                        (BatchEncoding).
        labels: list of list of integer labels (list of list of int).

    Returns: list of features to model (list of CustomInputFeatures).

    """

    features = []
    for b, l in enumerate(labels):
        inputs = {k: batch_encoding[k][b] for k in batch_encoding.keys()}
        feature = dict(**inputs, labels=l)
        features.append(feature)

    return features

def compute_f1_accuracy(preds: np.array, labels: np.array) -> dict:
    """
    Compute both f1 and accuracy for labels vs preds.
    Args:
        preds: array of prediction from model (numpy.array).
        labels: array of labels (numpy.array).

    Returns: dict with macro-f1 (f1) and accuracy (acc).

    """

    f1 = precision_recall_fscore_support(labels, preds, average='macro')  # macro F1 for evaluating the model
    acc = accuracy_score(labels, preds)

    return {
        'P': f1[0],
        'R': f1[1],
        'F1': f1[2],
        'acc': acc
    }
    
def token_classification_compute_metrics(
    pred: EvalPrediction
) -> dict:
    """
    Metric functions for token classifcation task for transformers' Trainer.

    Args:
        pred: object with label_ids and predictions as array attributes
              (transformers.EvalPrediction).

    Returns: dict with macro-F1 and accuracy.

    """
    global predd  # we could use this variable to check our predictions and labels, this will tell us their shapes
    predd = pred

    labels = pred.label_ids.reshape((-1,))  # Change all labels [batch_size, len(tokens)] to 1-D array
    preds = np.argmax(pred.predictions, axis=2).reshape((-1,))  # Choose the name entity with highest probability and map to 1D
                                                                # [batch_size, len(tokens), len(name_entities)]

    return compute_f1_accuracy(preds, labels)

In [5]:
model_name = "microsoft/deberta-large"  # Choose the huggingface models

In [6]:
tokenizer = AutoTokenizer.from_pretrained(model_name)  # Load tokenization

In [7]:
# Tokenize all utterances, tokenize all utterances to numbers
X_tok_train = tokenizer.batch_encode_plus(X_train.tolist(), max_length=200, truncation=True, padding="longest", return_tensors="pt")
X_tok_valid = tokenizer.batch_encode_plus(X_valid.tolist(), max_length=200, truncation=True, padding="longest", return_tensors="pt")

In [8]:
# Collect all name entities
tags = set(" ".join(df["ne_tokens"].values).split(" "))
# tags = set(y_train.apply(pd.Series).stack().reset_index(drop = True))
print(len(tags))

tag2id = {val: i for i, val in enumerate(tags)}
id2tag = {i: val for i, val in enumerate(tags)}

144

In [9]:
# Convert name entities to a numerical format
y_tok_train = encode_and_pad_y(X_tok_train, y_train.tolist(), tag2id)
y_tok_valid = encode_and_pad_y(X_tok_valid, y_valid.tolist(), tag2id)

In [10]:
# sanity check
assert len(X_tok_train['input_ids']) == len(y_tok_train)
assert len(X_tok_train['input_ids'][10]) == len(y_tok_train[10])
assert len(X_tok_valid['input_ids']) == len(y_tok_valid)
assert len(X_tok_valid['input_ids'][10]) == len(y_tok_valid[10])

In [11]:
# Concatenate tokenized X and y
train_dataset = tokens2features(X_tok_train, torch.tensor(y_tok_train))
valid_dataset = tokens2features(X_tok_valid, torch.tensor(y_tok_valid))

In [12]:
n_train_dataset = len(y_train)

In [13]:
train_dataset[10]

{'input_ids': tensor([    1,  8015, 12657,  4871,    31,  1855, 42938,     7,  3774, 20285,
           293,   662,     2,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0]),
 'token_type_ids': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 'labels': tensor([ 75, 101,  32,  32,  65,  83,  32,  79,  13,  13,  61,  32,  32,  32,
          32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,
          32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,
          32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,
          32,  32,  32])}

In [14]:
args = dict(
    output_dir="ner_model",
    num_train_epochs=15,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    learning_rate=5e-6,
    fp16=True,
    group_by_length=True,
    metric_for_best_model='eval_loss',
    load_best_model_at_end=False,
    #report_to="mlflow"
)

In [15]:
NB_STEPS = int(n_train_dataset / args["per_device_train_batch_size"]) + 1

eval_factor = 1
save_factor = 1

train_args = TrainingArguments(
    overwrite_output_dir=True,
    warmup_steps=min(500, int(NB_STEPS)),
    eval_steps=int(NB_STEPS/eval_factor),
    logging_steps=int(NB_STEPS/eval_factor),
    evaluation_strategy="steps",
    save_steps=save_factor * NB_STEPS,
    save_total_limit=3, # Limit to 1 for large models
    **args
)

In [16]:
model = AutoModelForTokenClassification.from_pretrained(
    model_name, 
    num_labels=len(tags), 
    id2label=id2tag,
    label2id=tag2id,
)

Some weights of the model checkpoint at microsoft/deberta-large were not used when initializing DebertaForTokenClassification: ['lm_predictions.lm_head.bias', 'lm_predictions.lm_head.dense.weight', 'lm_predictions.lm_head.dense.bias', 'lm_predictions.lm_head.LayerNorm.weight', 'lm_predictions.lm_head.LayerNorm.bias', 'deberta.embeddings.position_embeddings.weight']
- This IS expected if you are initializing DebertaForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DebertaForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DebertaForTokenClassification were not initialized from the model checkpoint at microsoft/deberta-large and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [51]:
trainer = Trainer(
        model=model,
        tokenizer=tokenizer,
        args=train_args,
        train_dataset=train_dataset,
        eval_dataset=valid_dataset,
        compute_metrics=token_classification_compute_metrics
)

In [52]:
mlflow.end_run()

In [53]:
try:
    trainer.train()
except RuntimeError as e:
    print(e)
except mlflow.exceptions.MlflowException:
    mlflow.end_run()

Trainer is attempting to log a value of "{0: 'B-stoploc.city_name', 1: 'I-airport_name', 2: 'I-fromloc.airport_name', 3: 'B-cost_relative', 4: 'I-toloc.airport_name', 5: 'B-restriction_code', 6: 'I-depart_date.day_name', 7: 'B-return_date.month_name', 8: 'B-round_trip', 9: 'B-arrive_time.period_mod', 10: 'B-today_relative', 11: 'I-round_trip', 12: 'I-transport_type', 13: 'I-toloc.city_name', 14: 'I-day_name', 15: 'B-return_time.period_mod', 16: 'B-return_date.day_number', 17: 'B-days_code', 18: 'I-return_date.today_relative', 19: 'I-arrive_time.time', 20: 'B-depart_time.time_relative', 21: 'I-stoploc.airport_name', 22: 'B-fromloc.airport_name', 23: 'B-depart_time.time', 24: 'B-toloc.country_name', 25: 'I-economy', 26: 'B-depart_date.today_relative', 27: 'I-arrive_date.day_number', 28: 'I-aircraft_code', 29: 'B-city_name', 30: 'I-fare_amount', 31: 'I-airline_code', 32: 'O', 33: 'B-state_name', 34: 'B-depart_time.start_time', 35: 'I-cost_relative', 36: 'B-depart_date.date_relative', 37: 'B-arrive_date.today_relative', 38: 'B-depart_time.period_mod', 39: 'I-depart_date.day_number', 40: 'I-return_date.date_relative', 41: 'I-mod', 42: 'B-depart_date.month_name', 43: 'I-return_date.month_name', 44: 'B-day_name', 45: 'I-depart_date.today_relative', 46: 'B-fromloc.state_name', 47: 'I-fromloc.airport_code', 48: 'I-flight_stop', 49: 'B-depart_date.year', 50: 'I-arrive_date.day_name', 51: 'B-return_date.date_relative', 52: 'B-time_relative', 53: 'B-stoploc.airport_code', 54: 'B-arrive_time.time_relative', 55: 'B-stoploc.state_code', 56: 'B-fare_basis_code', 57: 'I-arrive_time.time_relative', 58: 'B-airport_name', 59: 'I-toloc.country_name', 60: 'I-stoploc.airport_code', 61: 'B-depart_time.period_of_day', 62: 'I-time', 63: 'B-airport_code', 64: 'I-depart_date.month_name', 65: 'B-fromloc.city_name', 66: 'I-meal_description', 67: 'B-depart_date.day_number', 68: 'B-booking_class', 69: 'B-return_date.day_name', 70: 'B-arrive_time.time', 71: 'I-state_name', 72: 'B-connect', 73: 'I-fare_basis_code', 74: 'B-flight_time', 75: 'B-airline_name', 76: 'B-arrive_date.date_relative', 77: 'I-month_name', 78: 'B-arrive_date.month_name', 79: 'B-toloc.city_name', 80: 'I-flight_number', 81: 'B-flight_number', 82: 'I-arrive_time.end_time', 83: 'I-fromloc.city_name', 84: 'B-stoploc.airport_name', 85: 'B-toloc.state_name', 86: 'I-flight_time', 87: 'B-arrive_time.start_time', 88: 'I-toloc.airport_code', 89: 'B-depart_date.day_name', 90: 'B-flight_stop', 91: 'B-fromloc.state_code', 92: 'B-or', 93: 'B-meal_code', 94: 'I-arrive_date.month_name', 95: 'I-return_date.day_name', 96: 'B-aircraft_code', 97: 'B-toloc.airport_name', 98: 'B-arrive_date.day_name', 99: 'I-toloc.state_name', 100: 'B-flight', 101: 'I-airline_name', 102: 'I-depart_time.time_relative', 103: 'B-depart_time.end_time', 104: 'I-city_name', 105: 'I-return_date.day_number', 106: 'B-arrive_time.period_of_day', 107: 'I-depart_time.end_time', 108: 'B-transport_type', 109: 'I-arrive_time.period_of_day', 110: 'I-restriction_code', 111: 'I-arrive_time.start_time', 112: 'B-return_time.period_of_day', 113: 'B-month_name', 114: 'B-flight_mod', 115: 'B-return_date.today_relative', 116: 'B-day_number', 117: 'I-depart_time.time', 118: 'B-fromloc.airport_code', 119: 'B-toloc.state_code', 120: 'B-mod', 121: 'B-airline_code', 122: 'I-airport_code', 123: 'I-fromloc.state_name', 124: 'I-flight_mod', 125: 'B-flight_days', 126: 'B-period_of_day', 127: 'I-depart_time.period_of_day', 128: 'B-arrive_date.day_number', 129: 'B-meal', 130: 'B-compartment', 131: 'I-today_relative', 132: 'B-class_type', 133: 'I-depart_time.start_time', 134: 'B-arrive_time.end_time', 135: 'I-meal_code', 136: 'B-toloc.airport_code', 137: 'B-meal_description', 138: 'I-class_type', 139: 'B-economy', 140: 'B-state_code', 141: 'I-stoploc.city_name', 142: 'B-fare_amount', 143: 'B-time'}" for key "id2label" as a parameter. MLflow's log_param() only accepts values no longer than 250 characters so we dropped this attribute.
Trainer is attempting to log a value of "{'B-stoploc.city_name': 0, 'I-airport_name': 1, 'I-fromloc.airport_name': 2, 'B-cost_relative': 3, 'I-toloc.airport_name': 4, 'B-restriction_code': 5, 'I-depart_date.day_name': 6, 'B-return_date.month_name': 7, 'B-round_trip': 8, 'B-arrive_time.period_mod': 9, 'B-today_relative': 10, 'I-round_trip': 11, 'I-transport_type': 12, 'I-toloc.city_name': 13, 'I-day_name': 14, 'B-return_time.period_mod': 15, 'B-return_date.day_number': 16, 'B-days_code': 17, 'I-return_date.today_relative': 18, 'I-arrive_time.time': 19, 'B-depart_time.time_relative': 20, 'I-stoploc.airport_name': 21, 'B-fromloc.airport_name': 22, 'B-depart_time.time': 23, 'B-toloc.country_name': 24, 'I-economy': 25, 'B-depart_date.today_relative': 26, 'I-arrive_date.day_number': 27, 'I-aircraft_code': 28, 'B-city_name': 29, 'I-fare_amount': 30, 'I-airline_code': 31, 'O': 32, 'B-state_name': 33, 'B-depart_time.start_time': 34, 'I-cost_relative': 35, 'B-depart_date.date_relative': 36, 'B-arrive_date.today_relative': 37, 'B-depart_time.period_mod': 38, 'I-depart_date.day_number': 39, 'I-return_date.date_relative': 40, 'I-mod': 41, 'B-depart_date.month_name': 42, 'I-return_date.month_name': 43, 'B-day_name': 44, 'I-depart_date.today_relative': 45, 'B-fromloc.state_name': 46, 'I-fromloc.airport_code': 47, 'I-flight_stop': 48, 'B-depart_date.year': 49, 'I-arrive_date.day_name': 50, 'B-return_date.date_relative': 51, 'B-time_relative': 52, 'B-stoploc.airport_code': 53, 'B-arrive_time.time_relative': 54, 'B-stoploc.state_code': 55, 'B-fare_basis_code': 56, 'I-arrive_time.time_relative': 57, 'B-airport_name': 58, 'I-toloc.country_name': 59, 'I-stoploc.airport_code': 60, 'B-depart_time.period_of_day': 61, 'I-time': 62, 'B-airport_code': 63, 'I-depart_date.month_name': 64, 'B-fromloc.city_name': 65, 'I-meal_description': 66, 'B-depart_date.day_number': 67, 'B-booking_class': 68, 'B-return_date.day_name': 69, 'B-arrive_time.time': 70, 'I-state_name': 71, 'B-connect': 72, 'I-fare_basis_code': 73, 'B-flight_time': 74, 'B-airline_name': 75, 'B-arrive_date.date_relative': 76, 'I-month_name': 77, 'B-arrive_date.month_name': 78, 'B-toloc.city_name': 79, 'I-flight_number': 80, 'B-flight_number': 81, 'I-arrive_time.end_time': 82, 'I-fromloc.city_name': 83, 'B-stoploc.airport_name': 84, 'B-toloc.state_name': 85, 'I-flight_time': 86, 'B-arrive_time.start_time': 87, 'I-toloc.airport_code': 88, 'B-depart_date.day_name': 89, 'B-flight_stop': 90, 'B-fromloc.state_code': 91, 'B-or': 92, 'B-meal_code': 93, 'I-arrive_date.month_name': 94, 'I-return_date.day_name': 95, 'B-aircraft_code': 96, 'B-toloc.airport_name': 97, 'B-arrive_date.day_name': 98, 'I-toloc.state_name': 99, 'B-flight': 100, 'I-airline_name': 101, 'I-depart_time.time_relative': 102, 'B-depart_time.end_time': 103, 'I-city_name': 104, 'I-return_date.day_number': 105, 'B-arrive_time.period_of_day': 106, 'I-depart_time.end_time': 107, 'B-transport_type': 108, 'I-arrive_time.period_of_day': 109, 'I-restriction_code': 110, 'I-arrive_time.start_time': 111, 'B-return_time.period_of_day': 112, 'B-month_name': 113, 'B-flight_mod': 114, 'B-return_date.today_relative': 115, 'B-day_number': 116, 'I-depart_time.time': 117, 'B-fromloc.airport_code': 118, 'B-toloc.state_code': 119, 'B-mod': 120, 'B-airline_code': 121, 'I-airport_code': 122, 'I-fromloc.state_name': 123, 'I-flight_mod': 124, 'B-flight_days': 125, 'B-period_of_day': 126, 'I-depart_time.period_of_day': 127, 'B-arrive_date.day_number': 128, 'B-meal': 129, 'B-compartment': 130, 'I-today_relative': 131, 'B-class_type': 132, 'I-depart_time.start_time': 133, 'B-arrive_time.end_time': 134, 'I-meal_code': 135, 'B-toloc.airport_code': 136, 'B-meal_description': 137, 'I-class_type': 138, 'B-economy': 139, 'B-state_code': 140, 'I-stoploc.city_name': 141, 'B-fare_amount': 142, 'B-time': 143}" for key "label2id" as a parameter. MLflow's log_param() only accepts values no longer than 250 characters so we dropped this attribute.

Attempted to log scalar metric loss:
0.0091
Attempted to log scalar metric learning_rate:
4.701589920503975e-06
Attempted to log scalar metric epoch:
1.0
Attempted to log scalar metric eval_loss:
0.04734525457024574
Attempted to log scalar metric eval_P:
0.9147428798133669
Attempted to log scalar metric eval_R:
0.8935448934405739
Attempted to log scalar metric eval_F1:
0.8984542618716855
Attempted to log scalar metric eval_acc:
0.9972444444444445
Attempted to log scalar metric eval_runtime:
14.6061
Attempted to log scalar metric eval_samples_per_second:
34.232
Attempted to log scalar metric epoch:
1.0

/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

KeyboardInterrupt:

# Evaluation

In [142]:
def batch(iterable, batch_size):
    l = len(iterable)
    
    for i in range(0, l, batch_size):
        yield iterable[i: min(i + batch_size, l)]

def get_predictions(
    model,
    tokenizer,
    dataset,
    classes: dict,
    device: str = "cuda",
    max_length: int = 200,
    batch_size: int = 1,
) -> np.array:
    
    model.eval()
    model.to(device)
    torch.set_num_threads(8)
    
    collate = DataCollatorWithPadding(tokenizer=tokenizer, padding="longest", max_length=max_length)
    
    with torch.no_grad():
        y_pred = np.array([])
        
        with tqdm(total=len(dataset)) as pgbar:
            for batch_datapoint in batch(dataset, batch_size):
                collate_datapoint = collate(batch_datapoint)
                
                output = model(**{k: v.to(device) for k, v in collate_datapoint.items() if k in {"input_ids", "attention_mask"}})
                
                pred = output.logits.detach().cpu().numpy()
                
                if len(y_pred) == 0:
                    y_pred = pred
                else:
                    y_pred = np.concatenate((y_pred, pred))
                
                pgbar.update(batch_size)
    
    return y_pred

def id2tags(pred: np.array, mapping: dict) -> list:
    pred_ne_tokens = []
    
    for i, datapoint in enumerate(pred):
        pred_ne_tokens.append([mapping[i] for i in datapoint])
    
    return pred_ne_tokens

In [82]:
eval_model_name = "../models/ner_model_v1/"

In [83]:
model_eval = AutoModelForTokenClassification.from_pretrained(eval_model_name)

In [84]:
X_tok_test = tokenizer.batch_encode_plus(X_test.tolist(), max_length=200, padding="longest", truncation=True, return_tensors="pt")

In [87]:
y_tok_test = encode_and_pad_y(X_tok_test, y_test.tolist(), tag2id)

In [88]:
test_dataset = tokens2features(X_tok_test, y_tok_test)

In [96]:
X_pred = get_predictions(model_eval, tokenizer, test_dataset, tags, batch_size=1)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 893/893 [00:27<00:00, 31.91it/s]

In [128]:
report = classification_report(
    np.reshape(X_pred.argmax(-1), newshape=(-1,)),
    np.reshape(y_tok_test, newshape=(-1,)),
    labels=list(id2tag.keys()),
    target_names=list(id2tag.values()),
    zero_division=0,
    output_dict=False,
)

In [130]:
print(report)

                              precision    recall  f1-score   support

         B-stoploc.city_name       1.00      1.00      1.00        20
              I-airport_name       0.40      0.78      0.53        27
      I-fromloc.airport_name       1.00      0.45      0.62        64
             B-cost_relative       0.97      1.00      0.99        36
        I-toloc.airport_name       1.00      1.00      1.00         5
          B-restriction_code       1.00      1.00      1.00         4
      I-depart_date.day_name       0.99      0.98      0.99       215
    B-return_date.month_name       0.00      0.00      0.00         0
                B-round_trip       0.97      1.00      0.99        71
    B-arrive_time.period_mod       0.00      0.00      0.00         0
            B-today_relative       0.00      0.00      0.00         0
                I-round_trip       1.00      1.00      1.00        71
            I-transport_type       1.00      1.00      1.00        11
           I-toloc.city_name       0.99      0.97      0.98      1091
                  I-day_name       0.00      0.00      0.00         0
    B-return_time.period_mod       0.00      0.00      0.00         0
    B-return_date.day_number       0.00      0.00      0.00         0
                 B-days_code       1.00      1.00      1.00         1
I-return_date.today_relative       0.00      0.00      0.00         0
          I-arrive_time.time       1.00      0.97      0.99        39
 B-depart_time.time_relative       0.98      0.98      0.98        65
      I-stoploc.airport_name       0.00      0.00      0.00         0
      B-fromloc.airport_name       1.00      0.48      0.65        25
          B-depart_time.time       1.00      0.89      0.94        64
        B-toloc.country_name       1.00      1.00      1.00         1
                   I-economy       0.00      0.00      0.00         0
B-depart_date.today_relative       1.00      1.00      1.00         9
    I-arrive_date.day_number       0.00      0.00      0.00         1
             I-aircraft_code       1.00      1.00      1.00        36
                 B-city_name       0.54      0.82      0.65        38
               I-fare_amount       1.00      1.00      1.00         2
              I-airline_code       0.93      0.82      0.87        17
                           O       1.00      1.00      1.00     35105
                B-state_name       0.00      0.00      0.00         0
    B-depart_time.start_time       1.00      1.00      1.00         3
             I-cost_relative       0.86      1.00      0.92         6
 B-depart_date.date_relative       1.00      1.00      1.00        17
B-arrive_date.today_relative       0.00      0.00      0.00         0
    B-depart_time.period_mod       1.00      0.83      0.91         6
    I-depart_date.day_number       0.96      1.00      0.98        23
 I-return_date.date_relative       0.00      0.00      0.00         0
                       I-mod       0.00      0.00      0.00         0
    B-depart_date.month_name       0.96      0.98      0.97        55
    I-return_date.month_name       0.00      0.00      0.00         0
                  B-day_name       0.00      0.00      0.00         0
I-depart_date.today_relative       0.00      0.00      0.00         0
        B-fromloc.state_name       0.94      1.00      0.97        16
      I-fromloc.airport_code       1.00      0.64      0.78        14
               I-flight_stop       1.00      1.00      1.00        21
          B-depart_date.year       1.00      1.00      1.00         3
      I-arrive_date.day_name       1.00      0.79      0.88        14
 B-return_date.date_relative       0.00      0.00      0.00         0
             B-time_relative       0.00      0.00      0.00         0
      B-stoploc.airport_code       0.00      0.00      0.00         0
 B-arrive_time.time_relative       0.94      0.94      0.94        31
        B-stoploc.state_code       0.00      0.00      0.00         0
           B-fare_basis_code       1.00      0.89      0.94        19
 I-arrive_time.time_relative       1.00      1.00      1.00         4
              B-airport_name       0.43      0.82      0.56        11
        I-toloc.country_name       1.00      1.00      1.00         1
      I-stoploc.airport_code       0.00      0.00      0.00         0
 B-depart_time.period_of_day       0.93      0.98      0.96       123
                      I-time       0.00      0.00      0.00         0
              B-airport_code       0.33      0.60      0.43         5
    I-depart_date.month_name       0.96      0.98      0.97        55
         B-fromloc.city_name       1.00      0.98      0.99       715
          I-meal_description       0.00      0.00      0.00         0
    B-depart_date.day_number       0.96      0.98      0.97        54
             B-booking_class       0.00      0.00      0.00         0
      B-return_date.day_name       0.00      0.00      0.00         0
          B-arrive_time.time       1.00      0.94      0.97        36
                I-state_name       0.00      0.00      0.00         0
                   B-connect       1.00      1.00      1.00         6
           I-fare_basis_code       1.00      1.00      1.00         7
               B-flight_time       1.00      1.00      1.00         1
              B-airline_name       0.98      1.00      0.99        99
 B-arrive_date.date_relative       1.00      1.00      1.00         2
                I-month_name       0.00      0.00      0.00         0
    B-arrive_date.month_name       0.83      0.71      0.77         7
           B-toloc.city_name       0.99      0.97      0.98       735
             I-flight_number       0.89      1.00      0.94         8
             B-flight_number       1.00      0.79      0.88        14
      I-arrive_time.end_time       1.00      1.00      1.00         8
         I-fromloc.city_name       1.00      0.98      0.99      1018
      B-stoploc.airport_name       0.00      0.00      0.00         0
          B-toloc.state_name       0.86      0.96      0.91        25
               I-flight_time       1.00      1.00      1.00         1
    B-arrive_time.start_time       1.00      1.00      1.00         8
        I-toloc.airport_code       1.00      1.00      1.00         5
      B-depart_date.day_name       0.99      0.99      0.99       212
               B-flight_stop       1.00      1.00      1.00        21
        B-fromloc.state_code       1.00      1.00      1.00        23
                        B-or       1.00      0.38      0.55         8
                 B-meal_code       0.00      0.00      0.00         0
    I-arrive_date.month_name       0.83      0.71      0.77         7
      I-return_date.day_name       0.00      0.00      0.00         0
             B-aircraft_code       0.94      1.00      0.97        31
        B-toloc.airport_name       1.00      1.00      1.00         3
      B-arrive_date.day_name       1.00      0.79      0.88        14
          I-toloc.state_name       0.89      0.91      0.90        43
                    B-flight       0.00      0.00      0.00         0
              I-airline_name       1.00      0.98      0.99       111
 I-depart_time.time_relative       0.00      0.00      0.00         0
      B-depart_time.end_time       1.00      1.00      1.00         3
                 I-city_name       0.48      0.80      0.60        54
    I-return_date.day_number       0.00      0.00      0.00         0
 B-arrive_time.period_of_day       1.00      0.75      0.86         8
      I-depart_time.end_time       1.00      1.00      1.00         3
            B-transport_type       1.00      1.00      1.00        10
 I-arrive_time.period_of_day       0.00      0.00      0.00         0
          I-restriction_code       1.00      1.00      1.00         4
    I-arrive_time.start_time       1.00      1.00      1.00         1
 B-return_time.period_of_day       0.00      0.00      0.00         0
                B-month_name       0.00      0.00      0.00         0
                B-flight_mod       1.00      1.00      1.00        24
B-return_date.today_relative       0.00      0.00      0.00         0
                B-day_number       0.00      0.00      0.00         0
          I-depart_time.time       1.00      1.00      1.00        55
      B-fromloc.airport_code       1.00      0.50      0.67        10
          B-toloc.state_code       1.00      1.00      1.00        18
                       B-mod       0.50      1.00      0.67         1
              B-airline_code       1.00      0.89      0.94        38
              I-airport_code       0.33      0.60      0.43         5
        I-fromloc.state_name       0.94      0.94      0.94        32
                I-flight_mod       0.17      1.00      0.29         1
               B-flight_days       1.00      1.00      1.00        10
             B-period_of_day       0.00      0.00      0.00         0
 I-depart_time.period_of_day       1.00      1.00      1.00         1
    B-arrive_date.day_number       0.83      0.71      0.77         7
                      B-meal       1.00      0.94      0.97        17
               B-compartment       0.00      0.00      0.00         0
            I-today_relative       0.00      0.00      0.00         0
                B-class_type       1.00      0.96      0.98        25
    I-depart_time.start_time       1.00      1.00      1.00         1
      B-arrive_time.end_time       1.00      1.00      1.00         8
                 I-meal_code       0.00      0.00      0.00         0
        B-toloc.airport_code       0.75      1.00      0.86         3
          B-meal_description       1.00      1.00      1.00        10
                I-class_type       1.00      1.00      1.00        17
                   B-economy       0.83      1.00      0.91         5
                B-state_code       1.00      1.00      1.00         1
         I-stoploc.city_name       1.00      1.00      1.00        37
               B-fare_amount       1.00      1.00      1.00         2
                      B-time       0.00      0.00      0.00         0

                   micro avg       0.99      0.99      0.99     41078
                   macro avg       0.65      0.64      0.64     41078
                weighted avg       1.00      0.99      0.99     41078

In [159]:
def get_pred_ne(text: str, pred_no_tokens: list) -> str:
    tokens = tokenizer.tokenize(text)
    
    index = 0
    token_pos = []
    pred_ne = []

    for i, token in enumerate(tokens):
        if i == 0 or token.startswith("Ä "):
            token_pos.append(0)
            
            pred_ne.append(pred_no_tokens[i])
            index += 1
    
    return " ".join(pred_ne)

In [169]:
test_df["pred_ne_tokens"] = id2tags(X_pred.argmax(-1), id2tag)
test_df

,text,ne,intent,ne_tokens,pred_ne_tokens
0,i would like to find a flight from charlotte t...,O O O O O O O O B-fromloc.city_name O B-toloc....,atis_flight,O O O O O O O O B-fromloc.city_name I-fromloc....,"[O, O, O, O, O, O, O, O, B-fromloc.city_name, ..."
1,on april first i need a ticket from tacoma to ...,O B-depart_date.month_name B-depart_date.day_n...,atis_airfare,O B-depart_date.month_name I-depart_date.month...,"[O, B-depart_date.month_name, I-depart_date.mo..."
2,on april first i need a flight going from phoe...,O B-depart_date.month_name B-depart_date.day_n...,atis_flight,O B-depart_date.month_name I-depart_date.month...,"[O, B-depart_date.month_name, I-depart_date.mo..."
3,i would like a flight traveling one way from p...,O O O O O O B-round_trip I-round_trip O B-from...,atis_flight,O O O O O O B-round_trip I-round_trip O B-from...,"[O, O, O, O, O, O, B-round_trip, I-round_trip,..."
4,i would like a flight from orlando to salt lak...,O O O O O O B-fromloc.city_name O B-toloc.city...,atis_flight,O O O O O O B-fromloc.city_name I-fromloc.city...,"[O, O, O, O, O, O, B-fromloc.city_name, I-from..."
...,...,...,...,...,...
888,please find all the flights from cincinnati to...,O O O O O O B-fromloc.city_name O O O O O B-to...,atis_flight,O O O O O O B-fromloc.city_name I-fromloc.city...,"[O, O, O, O, O, O, B-fromloc.city_name, I-from..."
889,find me a flight from cincinnati to any airpor...,O O O O O B-fromloc.city_name O O O O O B-tolo...,atis_flight,O O O O O B-fromloc.city_name I-fromloc.city_n...,"[O, O, O, O, O, B-fromloc.city_name, I-fromloc..."
890,i'd like to fly from miami to chicago on ameri...,O O O O O B-fromloc.city_name O B-toloc.city_n...,atis_flight,O O O O O O B-fromloc.city_name I-fromloc.city...,"[O, O, O, O, O, O, B-fromloc.city_name, I-from..."
891,i would like to book a round trip flight from ...,O O O O O O B-round_trip I-round_trip O O B-fr...,atis_flight,O O O O O O B-round_trip I-round_trip O O B-fr...,"[O, O, O, O, O, O, B-round_trip, I-round_trip,..."
892,find me a flight that flies from memphis to ta...,O O O O O O O B-fromloc.city_name O B-toloc.ci...,atis_flight,O O O O O O O B-fromloc.city_name I-fromloc.ci...,"[O, O, O, O, O, O, O, B-fromloc.city_name, I-f..."

In [170]:
a = test_df.apply(lambda df: get_pred_ne(df["text"], df["pred_ne_tokens"]), axis=1)
test_df.insert(2, "pred_ne", a)
test_df

,text,ne,pred_ne,intent,ne_tokens,pred_ne_tokens
0,i would like to find a flight from charlotte t...,O O O O O O O O B-fromloc.city_name O B-toloc....,O O O O O O O O B-fromloc.city_name O B-toloc....,atis_flight,O O O O O O O O B-fromloc.city_name I-fromloc....,"[O, O, O, O, O, O, O, O, B-fromloc.city_name, ..."
1,on april first i need a ticket from tacoma to ...,O B-depart_date.month_name B-depart_date.day_n...,O B-depart_date.month_name B-depart_date.day_n...,atis_airfare,O B-depart_date.month_name I-depart_date.month...,"[O, B-depart_date.month_name, I-depart_date.mo..."
2,on april first i need a flight going from phoe...,O B-depart_date.month_name B-depart_date.day_n...,O B-depart_date.month_name B-depart_date.day_n...,atis_flight,O B-depart_date.month_name I-depart_date.month...,"[O, B-depart_date.month_name, I-depart_date.mo..."
3,i would like a flight traveling one way from p...,O O O O O O B-round_trip I-round_trip O B-from...,O O O O O O B-round_trip I-round_trip O B-from...,atis_flight,O O O O O O B-round_trip I-round_trip O B-from...,"[O, O, O, O, O, O, B-round_trip, I-round_trip,..."
4,i would like a flight from orlando to salt lak...,O O O O O O B-fromloc.city_name O B-toloc.city...,O O O O O O B-fromloc.city_name O B-toloc.city...,atis_flight,O O O O O O B-fromloc.city_name I-fromloc.city...,"[O, O, O, O, O, O, B-fromloc.city_name, I-from..."
...,...,...,...,...,...,...
888,please find all the flights from cincinnati to...,O O O O O O B-fromloc.city_name O O O O O B-to...,O O O O O O B-fromloc.city_name O O O O O B-to...,atis_flight,O O O O O O B-fromloc.city_name I-fromloc.city...,"[O, O, O, O, O, O, B-fromloc.city_name, I-from..."
889,find me a flight from cincinnati to any airpor...,O O O O O B-fromloc.city_name O O O O O B-tolo...,O O O O O B-fromloc.city_name O O O O O B-tolo...,atis_flight,O O O O O B-fromloc.city_name I-fromloc.city_n...,"[O, O, O, O, O, B-fromloc.city_name, I-fromloc..."
890,i'd like to fly from miami to chicago on ameri...,O O O O O B-fromloc.city_name O B-toloc.city_n...,O O O O O B-fromloc.city_name O B-toloc.city_n...,atis_flight,O O O O O O B-fromloc.city_name I-fromloc.city...,"[O, O, O, O, O, O, B-fromloc.city_name, I-from..."
891,i would like to book a round trip flight from ...,O O O O O O B-round_trip I-round_trip O O B-fr...,O O O O O O B-round_trip I-round_trip O O B-fr...,atis_flight,O O O O O O B-round_trip I-round_trip O O B-fr...,"[O, O, O, O, O, O, B-round_trip, I-round_trip,..."
892,find me a flight that flies from memphis to ta...,O O O O O O O B-fromloc.city_name O B-toloc.ci...,O O O O O O O B-fromloc.city_name O B-toloc.ci...,atis_flight,O O O O O O O B-fromloc.city_name I-fromloc.ci...,"[O, O, O, O, O, O, O, B-fromloc.city_name, I-f..."

In [182]:
diff_test_df = test_df[test_df["ne"]!=test_df["pred_ne"]]
diff_test_df.index = range(len(diff_test_df))
diff_test_df

,text,ne,pred_ne,intent,ne_tokens,pred_ne_tokens
0,i need a flight from toronto to newark one way...,O O O O O B-fromloc.city_name O B-toloc.city_n...,O O O O O B-fromloc.city_name O B-toloc.city_n...,atis_flight,O O O O O B-fromloc.city_name I-fromloc.city_n...,"[O, O, O, O, O, B-fromloc.city_name, I-fromloc..."
1,on next wednesday flight from kansas city to c...,O B-depart_date.date_relative B-depart_date.da...,O B-depart_date.date_relative B-depart_date.da...,atis_flight,O B-depart_date.date_relative B-depart_date.da...,"[O, B-depart_date.date_relative, B-depart_date..."
2,find nonstop flights from salt lake city to ne...,O B-flight_stop O O B-fromloc.city_name I-from...,O B-flight_stop O O B-fromloc.city_name I-from...,atis_flight,O B-flight_stop I-flight_stop O O B-fromloc.ci...,"[O, B-flight_stop, I-flight_stop, O, O, B-from..."
3,what meals are served on american flight 665 6...,O B-meal O O O B-airline_name O B-flight_numbe...,O B-meal O O O B-airline_name O B-flight_numbe...,atis_meal,O B-meal O O O B-airline_name I-airline_name O...,"[O, B-meal, O, O, O, B-airline_name, I-airline..."
4,which flights leave newark after noon next sat...,O O O B-fromloc.city_name B-depart_time.time_r...,O O O B-fromloc.city_name B-depart_time.time_r...,atis_flight,O O O B-fromloc.city_name I-fromloc.city_name ...,"[O, O, O, B-fromloc.city_name, I-fromloc.city_..."
...,...,...,...,...,...,...
86,i need a flight leaving kansas city to chicago...,O O O O O B-fromloc.city_name I-fromloc.city_n...,O O O O O B-fromloc.city_name I-fromloc.city_n...,atis_flight,O O O O O B-fromloc.city_name I-fromloc.city_n...,"[O, O, O, O, O, B-fromloc.city_name, I-fromloc..."
87,can you find me a flight from salt lake city t...,O O O O O O O B-fromloc.city_name I-fromloc.ci...,O O O O O O O B-fromloc.city_name I-fromloc.ci...,atis_flight,O O O O O O O B-fromloc.city_name I-fromloc.ci...,"[O, O, O, O, O, O, O, B-fromloc.city_name, I-f..."
88,please find a flight round trip from los angel...,O O O O B-round_trip I-round_trip O B-fromloc....,O O O O B-round_trip I-round_trip O B-fromloc....,atis_flight,O O O O B-round_trip I-round_trip O B-fromloc....,"[O, O, O, O, B-round_trip, I-round_trip, O, B-..."
89,find me all the flights from milwaukee to st. ...,O O O O O O B-fromloc.city_name O B-city_name ...,O O O O O O B-fromloc.city_name O B-toloc.city...,atis_flight,O O O O O O B-fromloc.city_name I-fromloc.city...,"[O, O, O, O, O, O, B-fromloc.city_name, I-from..."
90,now show me all the flights from st. louis to ...,O O O O O O O B-city_name I-city_name O B-tolo...,O O O O O O O B-fromloc.city_name I-fromloc.ci...,atis_flight,O O O O O O O B-city_name I-city_name I-city_n...,"[O, O, O, O, O, O, O, B-fromloc.city_name, I-f..."

In [183]:
test_df.to_csv("../atis/result/atis_ner_inference.csv", index=False)

In [ ]:
test